### ISSUE TITLE
[Suggestion] Style the lyrics view.

### ISSUE THREAD

**Issue by aleeeee1** [SpotX-Official/SpotX-Bash#20]
Please add the possibility to patch lyrics colors too, similar to windows's version where it's dark background and green text. Reading the lyrics with red backgrounds really destroys my eyes. I wonder why Spotify doesn't patch it itself.

Thank you :D

**Comment by jetfir3** [comment]
At this time, UI customization is not something I wish to entertain with this project. Outside of hiding podcasts and episodes on the homescreen, nothing else with the UI is customized unless it's an official feature/setting.. and the only reason the podcast hiding is included is because it's a simple one-liner patch (for now anyway). 

I may reconsider this in the future, possible just removing color from lyrics background so it's always black background with grey/white letters... but picking and choosing colors is unlikely. 

Spicetify is always an option for those who wish to theme and customize the UI.

**Comment by jetfir3** [comment]
@aleeeee1 

I've added a new commandline argument to set lyrics background color to black, `-l` or `--lyricsnocolor` will trigger this.

The patch is targeting Spotify builds v1.2.0.1155 and up although only builds 1.2.19+ have been tested so far.
Users should consider this feature experimental until I have time to test more builds and see what new builds released in the future will look like. 

Option flag has been added into the README "Options" section, but will not be considered a permanent feature until the `-l` option in the README gets a hyperlink pointing to the FAQ with a proper explanation.

I will not be adding lyric color customization.  Users wanting UI customization and color theming should stick to Spicetify.
