### ISSUE TITLE
Old UI option not working

### ISSUE THREAD

**Issue by LordEnder-Kitty** [SpotX-Official/SpotX-Bash#29]
I dislike the fact that this moves the lyrics button over to the right sidebar and i've used other forks of SpotX before but they only got rid of the popups, not the actual between-song ads and i know that the old ui option fixes the lyrics button however when i use it in the terminal command it says "Warning: Old UI not supported in clients after v1.2.13.661...". how can a get around that?
also, i saw that there was older updates of this repo that say they work with my version of spotify (1.2.26.1187) such as [this](https://github.com/SpotX-Official/SpotX-Bash/blob/1643199e3b2065550ffba22727f9ff954bb90a70/spotx.sh) and i was wondering if using that would do it. i don't know how to get that one though so i can't test it. i can program but i don't know much about shell scripting at all.

**Comment by jetfir3** [comment]
Any other forks of SpotX are either unofficial, outdated or use commands from this repo. Windows is https://github.com/SpotX-Official/SpotX and mac/linux is https://github.com/SpotX-Official/SpotX-Bash

The title of this issue is misleading -- as the error message stated, the Old UI option requires 1.2.13.661 or earlier. Your client is too new. If you had a supported client, it would work. You being unable to use something does not mean the script is broken.. you just haven't read through the README and FAQ. 

1. Uninstall current client, install 1.2.13.661. This is what the `-V <version>` flag is for. 
2. Stay on current version (or any recent version) and enable developer mode and toggle the experimental feature to disable moving lyrics into the right sidebar. You want to disable `enableRightSidebarLyrics`

The README and FAQ explain everything outlined in this response. Read it. Apply it. 
Things covered in the README and FAQ do not belong here.
