### ISSUE TITLE
Asking for password?

### ISSUE THREAD

**Issue by magenata** [SpotX-Official/SpotX-Bash#30]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify version: 1.2.30.1135 
- OS: 13.2.1
- Shell: terminal
```

### 📝 Description

1.Whenrunning a new install of Spot X it says it needs a password...I have zero passwords on my machine so not sure how to resolve
2.
3.
...

### 🖥️ Terminal Input/Output

% bash <(curl -sSL https://spotx-official.github.io/run.sh)

████╗███╗  ███╗ █████╗█╗  █╗  ███╗  ██╗ ████╗█╗ █╗
█╔══╝█╔═█╗█╔══█╗╚═█╔═╝╚█╗█╔╝  █╔═█╗█╔═█╗█╔══╝█║ █║
████╗███╔╝█║  █║  █║   ╚█╔╝██╗███╔╝████║████╗████║
╚══█║█╔═╝ █║  █║  █║   █╔█╗╚═╝█╔═█╗█╔═█║╚══█║█╔═█║
████║█║   ╚███╔╝  █║  █╔╝ █╗  ███╔╝█║ █║████║█║ █║
╚═══╝╚╝    ╚══╝   ╚╝  ╚╝  ╚╝  ╚══╝ ╚╝ ╚╝╚═══╝╚╝ ╚╝

Latest supported version: 1.2.30.1135
Detected Spotify version: 1.2.30.1135

Warning: SpotX does not have write permission in Spotify directory.
Requesting sudo permission...
Password:

**Comment by jetfir3** [comment]
This is strange, especially for a macOS user. The script is checking for write permission throughout the Spotify app directory and one or more of the directories is reporting that there is no write permission. 

It's also strange that there is no password on the machine -- when an app or script requires elevated permissions before proceeding and a user/password or fingerprint box pops up, what do you provide it?

When running SpotX-Bash and getting to the point in the script which you have shared above... if you have an empty password set for the current user account, then leaving it blank and just hitting the enter/return key should allow the script to proceed. Have you tried this? 

I'm also curious to see the output of the following commands:
1. 
```
me="$(whoami)" && echo $me && dscl . -authonly $me "" && echo $?
```
2. 
```
ls -ld /Applications/Spotify.app
```
3. 
```
ls -l /Applications/Spotify.app/Contents/Resources/Apps/
```

You've also stated in this issue template that you've installed Spicetify -- is this correct?

**Comment by jetfir3** [comment]
Week with no reply = closing. 

This issue seems to come down to:
A. User account permissions differ from account which installed Spotify.app -- things may work better if you install the Spotify.app into your /Users/$USER/Applications/ directory instead of the main /Applications directory. If that directory does not yet exist run the following command then drag Spotify.app into that new directory:
```
mkdir /Users/$USER/Applications/
```
B. Set a password on your user account and if SpotX-Bash ever requests sudo password again, you can simply enter your password (assuming your account has admin permissions) -- this should be standard practice anyway, regardless of this specific SpotX-Bash issue. 

Regardless, whatever oddities are created due to a lack of user password being set and/or lack of permissions... this isn't something which will be fixed or handled by SpotX-Bash -- this is a specific issue on your own device. 

If further discussion is required, join the SpotX telegram community linked in the README for easier back-and-forth on this oddity.
