### ISSUE TITLE
Ran spotx-bash and got this error(CODESIGN)

### ISSUE THREAD

**Issue by insomnia-creator** [SpotX-Official/SpotX-Bash#31]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: 1.2.31.1205.g4d59ad7c for macOS(Apple Silicon)
- OS: 14.1 (23B2073)
- Shell: zsh
```

### 📝 Description

1. Run script
2. Open spotify
3. Error comes
...

### 🖥️ Terminal Input/Output

Running install script works all fine

### 📸 Screenshots

![CleanShot 2024-02-15 at 15 36 02@2x](https://github.com/SpotX-Official/SpotX-Bash/assets/69950985/c4c7702a-254a-43d0-bb76-7c0ac2f5bc78)

**Comment by jetfir3** [comment]
showing the exact input command used + script output is always helpful (and is requested in the Issues template). 

delete spotify app from applications directory. re-run spotx-bash with `--installmac` flag (plus any additional flags you may be using) to have spotx-bash reinstall and patch spotify. If issue still happens.. share the input command + script output via screenshot.

then we can begin resolving the issue.

**Comment by insomnia-creator** [comment]
![CleanShot 2024-02-16 at 06 23 58@2x](https://github.com/SpotX-Official/SpotX-Bash/assets/69950985/46421b08-ba9a-44e5-bc82-16be0678a13b)

![CleanShot 2024-02-16 at 06 24 23@2x](https://github.com/SpotX-Official/SpotX-Bash/assets/69950985/4c3bae52-e521-45a9-a677-af6f0f5bf5a6)

it runs fine but gives the error once i open

**Comment by jetfir3** [comment]
Thanks. And.. strange. Can you run the following commands and screenshot input/output?

1.
```
command -v codesign
```

2. 
```
codesign -dv /Applications/Spotify.app
```

3.
```
codesign -f --deep -s - /Applications/Spotify.app
```

**Comment by insomnia-creator** [comment]
I have codesign binary:
![CleanShot 2024-02-16 at 15 01 18@2x](https://github.com/SpotX-Official/SpotX-Bash/assets/69950985/cbcfe53f-bd75-4cee-a1c6-dd1d583d2682)
Command 2:
![CleanShot 2024-02-16 at 15 01 30@2x](https://github.com/SpotX-Official/SpotX-Bash/assets/69950985/110643d0-cf56-4c68-af3b-d3dc86f05f60)
Command 3:
![CleanShot 2024-02-16 at 15 02 06@2x](https://github.com/SpotX-Official/SpotX-Bash/assets/69950985/b11b637a-8c7b-45f8-bec0-fed8efc8ec69)
i've tried all of these commands before with no result,
![CleanShot 2024-02-16 at 15 02 28@2x](https://github.com/SpotX-Official/SpotX-Bash/assets/69950985/f100cfd7-a3c1-4d02-9829-defc920d0fbd)

**Comment by jetfir3** [comment]
> i've tried all of these commands before with no result, 
>
> SOLUTION: RUN INSTALL SCRIPT WITH TERMINAL(macos)
> 
> Maybe can we at least change script to prompt user if using terminal emulator?

and this is why it's always best to share all input/output when dealing with cli issues. your output from command `# 3` seems to explain exactly what's going on. 

It appears that due to how alacritty is treated by macOS (and how alacritty works with the system), some extended attributes are being attached to the Spotify app while SpotX-Bash is working with it. This causes issues when attempting to re-codesign and the codesign never succeeds and you run into issues such as those being reported on this page. 

I've updated the repo to address this. 

1. Please delete /Applications/Spotify.app and reattempt the following in Alacritty:
```
bash <(curl -sSL https://spotx-official.github.io/run.sh) --installmac
```
2. I would be surprised if Spotify crashes now -- but if it STILL crashes, supply the input/output of:
```
xattr -lr /Applications/Spotify.app
```
3. Your PR is working around the issue but not solving the actual problem -- this will be closed and not accepted. 

4. Even if all is now working for you, please report back.

**Comment by insomnia-creator** [comment]
It works all well, I've tried it with alacritty right now and it's working fine.
Thanks for your help.
