### ISSUE TITLE
Patch disappears after about 2 weeks

### ISSUE THREAD

**Issue by MrBeardedGuy** [SpotX-Official/SpotX-Bash#36]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Switzerland

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: 1.2.33.1039 MacOS (Intel)
- OS: Sosoma 14.4 
- Shell: zsh
```

### 📝 Description

1. Run `bash <(curl -sSL https://spotx-official.github.io/run.sh) -B --installmac` 
2. Install the latest available build (i.e 1.2.33.1039)
3. Mac OS shows dialog to allow Spotify to accept incoming connections and access to the download folder (see below)
4. Deny both dialogs
5. Use patched Spotify for about a couple of weeks with no ads
6. Observe no update during this period
7. Open again Spotify after 2 weeks
8. Mac OS shows again the dialogs as in point 3
4. Deny both dialogs in order to use Spotify
10. Spotify, now has ads even though the version is the same (1.2.33.1039)  
...
![image](https://github.com/SpotX-Official/SpotX-Bash/assets/36925949/b0e6bc1f-c9fe-47d1-b3f2-cd75ea6fdebd)

![image](https://github.com/SpotX-Official/SpotX-Bash/assets/36925949/5e9fcbc4-19eb-49f6-8aff-02e768f6b30e)

### 🖥️ Terminal Input/Output

```
➜  ~ bash <(curl -sSL https://spotx-official.github.io/run.sh) -B

████╗███╗  ███╗ █████╗█╗  █╗  ███╗  ██╗ ████╗█╗ █╗
█╔══╝█╔═█╗█╔══█╗╚═█╔═╝╚█╗█╔╝  █╔═█╗█╔═█╗█╔══╝█║ █║
████╗███╔╝█║  █║  █║   ╚█╔╝██╗███╔╝████║████╗████║
╚══█║█╔═╝ █║  █║  █║   █╔█╗╚═╝█╔═█╗█╔═█║╚══█║█╔═█║
████║█║   ╚███╔╝  █║  █╔╝ █╗  ███╔╝█║ █║████║█║ █║
╚═══╝╚╝    ╚══╝   ╚╝  ╚╝  ╚╝  ╚══╝ ╚╝ ╚╝╚═══╝╚╝ ╚╝

Latest supported version: 1.2.33.1042
Detected Spotify version: 1.2.33.1039

✔ Created backup
✔ Applied free-tier plan patches
✔ Enabled experimental features
✔ Blocked automatic updates
✔ Codesigned Spotify
✔ Finished```

### 📸 Screenshots

_No response_

**Comment by jetfir3** [comment]
Patches don't just disappear or undo themselves. Stock Spotify is being reinstalled/updated at some point which removes the patches due to files being overwritten. Now the question is how. 

Spotify's built-in client updater would **_never_** update itself to the same version. The client doesn't know if it's patched and try to "clean" itself or something. The client has a version number and checks Spotify's servers while the client is open and running every so often to see if a new version is out... if a new version is detected it will add a notice in your drop-down menu under the user icon asking if you want to download/install the update. If this is ignored long enough the client will eventually download the update and install the update after Spotify is closed (process killed, not minimized). 

So either:
- you didn't have 1.2.33.1039 installed 2 weeks ago and it was updated with the built-in updater
  - The patches to block updates are fully functional, so you would have forgotten to use `-B` flag 
- there's something else on your system installing/updating Spotify such as homebrew or some other 3rd-party tool/etc

The only thing that could be done to resolve this on my end would be if the patches related to blocking updates were not working and needed to be updated for the most recent clients. But, as I've explained above, it would be impossible for the built-in client updater to re-install the same exact version... so if you patched 1.2.33.1039 2 weeks ago and now 1.2.33.1039 is completely stock.. it has nothing to do with SpotX-Bash or even Spotify's built-in updater and something else is going on. 

The following three commands would help you track the dates of things...
```
ls -la /Applications/Spotify.app/Contents/Resources/Apps
```
```
ls -la /Applications/Spotify.app/Contents/MacOS/
```
```
ls -la /Applications/
```
With the first two command you should see .bak files which confirm SpotX-Bash was run and made backup files.. along with file modification dates. The third command would list everything in Applications but, more specifically, would show the date/time Spotify.app was installed. 

You'd need to note these dates/times and compare them to changes in the future if this were to happen again. 

This issue is outside the scope of the repo/script... something is happening on your system which is reinstalling stock Spotify or you didn't use `-B` like you thought you did.

**Comment by jetfir3** [comment]
Closing. No response in 7+ days. Everything that needed to be said is in the previous comment -- whatever is going on is not caused by SpotX-Bash.

**Comment by samuelawachie** [comment]
> The following three commands would help you track the dates of things...
> ls -la /Applications/Spotify.app/Contents/Resources/Apps
> ls -la /Applications/Spotify.app/Contents/MacOS/
> ls -la /Applications/

Hi, just was going through this issue, and noticed that you mentioned these folders as places to look to see if SpotX is installed and when.
Can someone run similar tests on Linux? After installing SpotX-Bash, and then installing Spicetify on top of it, I know that SpotX is working because it's blocking ads as it should. But there doesn't seem to be any files that I see in the filesystem to show that it is installed. 
In the Spotify client (I'm using an older one to be able to use the Old UI), there is also no indication that it is installed.
Is there any log files, or check using the terminal, or within Spotify client itself that I can do to indicate that SpotX-bash is installed without resorting to the symptoms (like checking that adblock is still functional and the like)?

**Comment by jetfir3** [comment]
@samuelawachie 

running the SpotX-Bash command would tell you if it's patched or not (script output will tell you it's already patched and exit).

Doing this would also tell you the app path Spotify is installed in. You can look in that path to view if there is a Spotify backup (this would also mean it's patched). 

I should also note that both SpotX and Spicetify do not guarantee proper function if both mods are used at once. ONLY SpotX should be used.. or ONLY Spicetify should be used. Using both and all expectations go out the window. And neither of us will entertain support issues when both are used.
