### ISSUE TITLE
Lyrics not syncing

### ISSUE THREAD

**Issue by fallenmaverick** [SpotX-Official/SpotX-Bash#41]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify version: Spotify for macOS (Apple Silicon) 1.2.37.701.ge66eb7bc
- OS: Sonoma 14.5
- Shell: zsh
```

### 📝 Description

Previously I was able to see lyrics in Spotify, but it's gone and shows the "explore premium" option. 
Very saddening

### 🖥️ Terminal Input/Output

Yes, that ran normally. 

### 📸 Screenshots

![CleanShot 2024-05-15 at 19 39 38@2x](https://github.com/SpotX-Official/SpotX-Bash/assets/50070351/a1750ec0-ac57-44ad-b7e0-3f0894fc3e1d)

**Comment by pingpongterminator300** [comment]
Did you solve it? Im facing same problem

**Comment by jetfir3** [comment]
As of July 30, 2024 Spotify has started to return full/synced lyrics for free tier members. 

Since we last checked, lyrics should be available to most users running desktop client version v1.2.36.955 or higher. It's likely this will expand to some older version numbers in the future but currently  too soon to say. Lyrics availability seems to be rolling out to accounts and is not based on region. If you do not yet have lyrics on v1.2.36.955 or higher, hopefully you will get them back soon.
