### ISSUE TITLE
SpotX-Bash not blocking ads anymore on Mac

### ISSUE THREAD

**Issue by divinedivinityy** [SpotX-Official/SpotX-Bash#42]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: Spotify for macOS (Intel)
1.2.38.720.ga4a70a0e
- OS: Ventura 13.6.7
- Shell: zsh
```

### 📝 Description

1.  Download **Spotify's latest version**
2. Download and run **newest version of SpotX-Bash**
3. Open Spotify
4. **Video ads and banners unblocked upon startup**
![Screenshot 2024-05-23 at 3 00 52 PM](https://github.com/SpotX-Official/SpotX-Bash/assets/130804608/41ee4ddf-4971-4cb8-954e-51adad234f89)
5. SpotX-Bash is running, but not blocking ads
6. Doesn't start blocking ads until command input is pasted and ran several times.
...
![Screenshot 2024-05-23 at 3 09 51 PM](https://github.com/SpotX-Official/SpotX-Bash/assets/130804608/3e47c8b7-3884-4b65-8f47-438315097e35)

### 🖥️ Terminal Input/Output

bash <(curl -sSL https://spotx-official.github.io/run.sh)
████╗███╗  ███╗ █████╗█╗  █╗  ███╗  ██╗ ████╗█╗ █╗
█╔══╝█╔═█╗█╔══█╗╚═█╔═╝╚█╗█╔╝  █╔═█╗█╔═█╗█╔══╝█║ █║
████╗███╔╝█║  █║  █║   ╚█╔╝██╗███╔╝████║████╗████║
╚══█║█╔═╝ █║  █║  █║   █╔█╗╚═╝█╔═█╗█╔═█║╚══█║█╔═█║
████║█║   ╚███╔╝  █║  █╔╝ █╗  ███╔╝█║ █║████║█║ █║
╚═══╝╚╝    ╚══╝   ╚╝  ╚╝  ╚╝  ╚══╝ ╚╝ ╚╝╚═══╝╚╝ ╚╝

Latest supported version: 1.2.38.720
Detected Spotify version: 1.2.38.720

✔ Created backup
✔ Applied free-tier plan patches
✔ Enabled experimental features
✔ Codesigned Spotify
✔ Finished

### 📸 Screenshots

![Screenshot 2024-05-23 at 3 00 52 PM](https://github.com/SpotX-Official/SpotX-Bash/assets/130804608/41ee4ddf-4971-4cb8-954e-51adad234f89)
![Screenshot 2024-05-23 at 3 04 52 PM](https://github.com/SpotX-Official/SpotX-Bash/assets/130804608/0cd20c67-53e7-46b7-9d55-2d78f76cbd68)
![Screenshot 2024-05-23 at 3 09 51 PM](https://github.com/SpotX-Official/SpotX-Bash/assets/130804608/3e47c8b7-3884-4b65-8f47-438315097e35)

I had to run the startup command three times when normally it would only take running the command once to get it to work. I've had issues with getting it to work on this imac more than any other imac I've used. It also seems like the program randomly stops working after not opening spotify for a few days and I have to re-run the commands again.

**Comment by divinedivinityy** [comment]
I also should add that every time I've ran the command I've never gotten any errors even though it doesn't seem to fully work until I've pasted the command several times.

**Comment by jetfir3** [comment]
Hard to say if there was a stock update in the queue or something. 

Ideally, you should be allowing SpotX-Bash to both install and patch the Spotify client.. while also blocking client updates. 

I would suggest:
- full uninstall using uninstall steps outlined in the TROUBLESHOOTING guide linked in your initial Issue template
- using SpotX-Bash to both install, patch and block Spotify automatic updates
```
bash <(curl -sSL https://spotx-official.github.io/run.sh) --installmac -B
```

The same command can be run each time you want to update Spotify to the latest version.. the latest version is always mentioned in the readme.

**Comment by jetfir3** [comment]
I've added additional handling in the script which now looks for any stock Spotify update files which were downloaded by the built-in auto-updater and waiting to be installed. 

The script will auto-delete any update files found on whichever user account the SpotX-Bash script is running on and will output any update paths for other user accounts if update files are found there.

Not only can stock update files be stored in your computers current user account, but any local user account which also shares the same Spotify installation. So if there are multiple users on the computer.. or just the default/main user is accessing Spotify and you haven't blocked auto-updates with SpotX-Bash -- the client can be updated after the next Spotify launch on whichever user-account has the stored stock update files. 

These stored auto-update files should be the only reason the client is showing all ad banners and premium upsell buttons (assuming the `-p` / `--premium` options weren't used by a free-tier user) and likely why you had to run the command multiple times before it worked. 

Spotify downloads update and stores it -> run SpotX-Bash -> launch Spotify -> stock update gets installed removing patches.. and so on. Using the `-B` option with SpotX-Bash stops the client from being able to download any updates, even if there are multiple users accessing the same client across computer user accounts. Or be prepared to deal with losing patches until patched again or patching multiple times when Spotify updates itself. 

I've concluded that disabling updates by default could be considered "destructive" so it will remain an optional argument for the foreseeable future.

------

Since the script worked for you in the end, the script is actually working and the only way it would not work or stop working is some form of the scenarios described above or in my previous comment.
