### ISSUE TITLE
how to active lyrics 

### ISSUE THREAD

**Issue by raphael-as** [SpotX-Official/SpotX-Bash#48]
can i get the full lyrics with this crack ?

**Comment by jetfir3** [comment]
Read FAQ and closed issues before opening Issues. 

https://github.com/SpotX-Official/SpotX-Bash/wiki/SpotX%E2%80%90Bash-FAQ#does-spotx-bash-provide-access-to-lyrics

**Comment by jetfir3** [comment]
As of July 30, 2024 Spotify has started to return full/synced lyrics for free tier members. 

Since we last checked, lyrics should be available to most users running desktop client version v1.2.36.955 or higher. It's likely this will expand to some older version numbers in the future but currently  too soon to say. Lyrics availability seems to be rolling out to accounts and is not based on region. If you do not yet have lyrics on v1.2.36.955 or higher, hopefully you will get them back soon.
