### ISSUE TITLE
liked songs only showing 10k out of the total 43k

### ISSUE THREAD

**Issue by davidlynchcigarettes** [SpotX-Official/SpotX-Bash#63]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: Spotify for macOS (Apple Silicon) 1.2.48.405
- OS: macOS Sonoma 14.5
- Shell: zsh
```

### 📝 Description

1. Go to liked songs
2. Expect to see all 43,213 songs
3. I only see 10,000 songs and the list ends
...

### 🖥️ Terminal Input/Output

I didnt use any commands. The only command I ever use is the main one for updating spotX each time spotify updates.

**Comment by jetfir3** [comment]
so as soon as you uninstall SpotX while using the exact same Spotify version number, all ~43k songs show up again?

**Comment by davidlynchcigarettes** [comment]
correct!!

**Comment by jetfir3** [comment]
Hmm. I've no way to attempt to test or correct this as I have no accounts with liked songs even close to that number. SpotX custom patches shouldn't be doing anything to affect this... so I would assume it's a toggled ON experimental setting causing an issue. 

1. Confirm the issue is related to experimental settings, use the `-e` flag to exclude all experimental settings.
```
bash <(curl -sSL https://spotx-official.github.io/run.sh) -e
```
This installs SpotX but doesn't enable any experimental features. 
- Do all liked songs show up? yes/no

2. Testing with previous versions can help narrow down when this issue started (using the `-V versionnumberhere` flag with the command). Versions can be found here - https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/ you'd be using the 1.2.xx.xxx number only version.. leaving off the `.gXXXXXXXX`
```
bash <(curl -sSL https://spotx-official.github.io/run.sh) -B -V 1.2.47.366
```
- Do all liked songs show up? yes/no
If no, what about 1.2.46.xxx, 1.2.45.xxx.. etc etc.. at what downgraded version do all liked songs show up again?

**Comment by davidlynchcigarettes** [comment]
yes they do!! thank u so much omg

**Comment by jetfir3** [comment]
> yes they do!! thank u so much omg

v1.2.49.439 came out today on macOS... I'm curious if you have all ~43k liked songs show up WITHOUT using the `-e` flag when running SpotX-Bash now?

**Comment by davidlynchcigarettes** [comment]
hey!! so im still pretty new to coding/programming stuff, and so the way
i've been using it since i first installed spotx bash is: every few weeks
or so when i finally see an ad in my spotify i'll just close spotify, copy
the main line of code from the github into my terminal and run it, and then
spotify works ad free for a good month before i need to paste and run the
code again. I thought this was "updating" it but from reading the github
more thoroughly I see that its supposed to auto update? either way, i'm not
entirely sure how to check what you want to know, cuz I went to go paste
and run the code since seeing this but I get "spot X is already installed"
or something.

**Comment by jetfir3** [comment]
> hey!! 

You have to run SpotX-Bash again every few weeks or so because you aren't blocking Spotify updates (this requires adding the `-B` flag to the end of the command)... so Spotify automatically updates itself at some point which overwrites the SpotX-Bash patches. 

It's perfectly fine to continue doing things that way.. letting Spotify update itself when it needs to -- just know it's not a matter of "SpotX-Bash stopped working out of nowhere" but that new Spotify updates erase all patches made since the client is updating all its files.  

Alternatively, you can have SpotX-Bash update your Spotify to the latest version instead by adding the `--installmac` flag to the command... this will install the latest version then patch it after installation. You could also add the "block updates" option.. but up to you. 
Example command would be:
```
bash <(curl -sSL https://spotx-official.github.io/run.sh) --installmac -B
```

or if you don't want to worry about remembering flags.. you can always use the -i (interactive) flag to run through things with you...
```
bash <(curl -sSL https://spotx-official.github.io/run.sh) -i
```
and you will be asked which features you want to apply.. including if you want to update to the latest version.

**Comment by davidlynchcigarettes** [comment]
all my liked songs show up now without using the "-e" :)
