### ISSUE TITLE
Can't run bash <(curl -sSL https://spotx-official.github.io/run.sh) - is the server down somehow?

### ISSUE THREAD

**Issue by leniel** [SpotX-Official/SpotX-Bash#65]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Brazil

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify version: Spotify for macOS (Apple Silicon) 1.2.50.335.g5e2860a8
- OS: Mac OS Sequoia 15.0.1
- Shell: Bash
```

### 📝 Description

bash <(curl -sSL https://spotx-official.github.io/run.sh) won't run at all...

curl - v returned: operation timed out "Couldn't connect to server"

### 🖥️ Terminal Input/Output

bash <(curl -sSL https://spotx-official.github.io/run.sh)

### 📸 Screenshots

<img width="640" alt="image" src="https://github.com/user-attachments/assets/c6ab9f8a-97a0-413f-8054-ca8714ff426d">

**Comment by leniel** [comment]
@jetfir3 my bad... I did a Crtl+F and searched for a given keyword that didn't bring the result... that explains it all.... even worse: it's the 4th link in the FAQ.

At least if someone searches for "timed out", "can't run" , "server down" they'll probably get here.

The script used to run just fine... I think I ran it last month without a problem.

For now I'll download the script and run locally.

Thanks for taking the time to answer. 👍🏻

**Comment by jetfir3** [comment]
you tried **both** links in the FAQ and neither are working?
that would suggest an issue on your ISP/network/computer side as GitHub is working without issue.

if running the script locally, chmod +x the file and running `sh spotx.sh` or bash spotx.sh` should work... otherwise something is up with your machine/setup.

**Comment by leniel** [comment]
This links opens just fine if I open a new browser tab:
https://raw.githubusercontent.com/SpotX-Official/SpotX-Bash/main/spotx.sh

While for this other one:
https://spotx-official.github.io/run.sh
the browser says "This site can’t be reached".

From the 1st script link I can see all the script's content - copied it to spotx.sh file:

<img width="762" alt="image" src="https://github.com/user-attachments/assets/c6db205d-0299-4f03-8bf8-bb8e375aced0">


...and then tried running locally:

<img width="574" alt="image" src="https://github.com/user-attachments/assets/fc020300-dcb9-4355-8977-9aa387f3782e">

It hangs there on the terminal with no success message at all.

Maybe I'm doing some command in the wrong way or the script it trying to reach a given URL online which is also being blocked? Going through the script's code I see URLs only on for the About section.

**Comment by leniel** [comment]
ha... good news... it sat there for awhile but succeeded! Usually when running the script online it applied the patch instantly and that lead me to think it was not working this time...

<img width="615" alt="image" src="https://github.com/user-attachments/assets/d197debc-eeb6-49e3-ba9f-0ebadf84af16">

**Comment by jetfir3** [comment]
> ha... good news... it sat there for awhile but succeeded! Usually when running the script online it applied the patch instantly and that lead me to think it was not working this time...

glad things worked in the end.. but it is strange that it didn't instantly run and seemed to hang at first. there shouldn't be much of a difference between running the script directly via curl or running locally.

since the `raw.githubusercontent` URL seemed to load on your computer.. why didn't you just run the following?
```
bash <(curl -sSL https://raw.githubusercontent.com/SpotX-Official/SpotX-Bash/main/spotx.sh)
```

does that not load/run in your terminal and only works in browser? if giving an error in Terminal.. what's the output?

**Comment by leniel** [comment]
If I call:

`bash <(curl -sSL https://raw.githubusercontent.com/SpotX-Official/SpotX-Bash/main/spotx.sh)`

it stays there with nothing happening like this:

<img width="621" alt="image" src="https://github.com/user-attachments/assets/0996740d-96b4-480b-a816-eab28792683c">

I got this printscreen 3 minutes after running the command... no error(s) at all.

After some time I checked the Terminal window and voilà:

<img width="619" alt="image" src="https://github.com/user-attachments/assets/a919432c-d0ba-4c09-ba1c-c03c7d39673a">

**Comment by jetfir3** [comment]
> If I call:
> 
> `bash <(curl -sSL https://raw.githubusercontent.com/SpotX-Official/SpotX-Bash/main/spotx.sh)`
> 
> it stays there with nothing happening like this:
> 
> After some time I checked the Terminal window and voilà:


Ok, so the backup command does run successfully.. it just is hanging for you.. similarly to when you previously ran the script locally with `bash spotx.sh` (although the script didn't repatch Spotify because it has already been patched -- hence the "warning" output). So this at least confirms that at least one of the commands mentioned in FAQ is working and doesn't require downloading and running the script locally.

This hanging delay is odd though. Nothing in the script should be causing the hang. The only thing I can think of is when the script is checking for the version of the currently installed Spotify before proceeding.. but this should only take a couple seconds. 

If you run the following command does it output the script version quickly.. or does it take awhile for the output as well?
```
bash <(curl -sSL https://raw.githubusercontent.com/SpotX-Official/SpotX-Bash/main/spotx.sh) -v
```

The version output command should happen instantly without 99% of the script being run.. so if it's also hanging then it would seem something is going on with your computer :-/

**Comment by leniel** [comment]
I just uploaded a video of about 2.5 min executing the command you mentioned in your last comment... as you see, it doesn't output anything immediately:

https://github.com/user-attachments/assets/b795f815-a8c4-477b-a150-baddfe64d391

**Comment by jetfir3** [comment]
Thanks for the video. Very weird...
the following command is a hello world script.. which should do nothing but output "Hello World!" instantly... does it also hang for you?
```
bash <(curl -sSL https://raw.githubusercontent.com/ruanyf/simple-bash-scripts/master/scripts/hello-world.sh)
```

**Comment by leniel** [comment]
the Hello World script runs immediately:


https://github.com/user-attachments/assets/772b61f8-16e3-41ff-ab61-49e189ce00de

**Comment by leniel** [comment]
aha... now it's instant to get the version and do the patching:

https://github.com/user-attachments/assets/fac8086c-5238-48bf-a024-cd54d4667ea3

thanks for the awesome work with SpotX!  :)
