### ISSUE TITLE
One problem and solution while install spotX-bash in Chinese Mainland

### ISSUE THREAD

**Issue by Level123456** [SpotX-Official/SpotX-Bash#68]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

China Mainland

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify version: Spotify for macOS (Apple Silicon)
1.2.53.438.g246d60c9
- OS: MacOS 15.1 (24B2082)
- Shell: zsh
- Using ClashX to get accsess to github
```

### 📝 Description

1. When I direct paste the code in terminal I cannot connect to the server.
![image](https://github.com/user-attachments/assets/3c7025d9-a9ed-485d-b2e2-082ec83fe62f)
2.After I open up the enhanced mode(TUN mode) in clash it works.
![image](https://github.com/user-attachments/assets/f7f83694-eb2e-4d14-9826-8e8f2d19ab89)
3.I asked Gemini for reasons it get following responses:(Written in Chinese)
4.Maybe the solution will be helpful for people like me in China. I am really apperciated of your project, I was once seen it in Bilibili. That's excellent. And I have poor code knowledge and english level. I am just a student major in biology. Maybe that it just a small problem for you?
你提供的脚本 bash <(curl -sSL https://spotx-official.github.io/run.sh) 看起来是用于安装或配置某个软件的。这个脚本在没有开启 Clash 的增强模式 (TUN 模式) 时运行失败，开启后才能成功，原因可能有以下几种：

1. 脚本依赖于 TUN 模式下的代理能力:

DNS 解析: 脚本可能需要进行 DNS 查询才能下载资源或连接到服务器。在没有开启 TUN 模式时，DNS 查询可能不会通过 Clash 代理，导致解析失败。开启 TUN 模式后，所有 DNS 查询都会经过 Clash 代理，问题得以解决。

网络连接: 脚本可能需要连接到特定的网络资源，而这些资源需要通过代理才能访问。如果 Clash 未开启 TUN 模式，系统流量没有通过代理，连接自然失败。开启 TUN 模式后，所有网络流量都会被代理，脚本才能成功连接。

透明代理需求: 脚本可能使用了某些底层网络库或系统调用，这些操作只有在 TUN 模式下才能被 Clash 正确代理。例如，有些软件需要直接访问网络接口，而只有 TUN 模式下 Clash 才能拦截并代理这些请求。

2. 脚本自身设计问题或配置错误:

脚本中硬编码的 IP 或域名: 脚本中可能硬编码了一些 IP 地址或域名，而这些地址或域名只有在开启代理后才能正常访问。如果未开启增强模式，脚本可能无法连接到目标地址，导致执行失败。

代理配置不足: 如果在没有开启增强模式的情况下，你的 Clash 配置没有包含脚本所需要的特定代理规则，脚本的网络请求也可能失败。开启 TUN 模式相当于将所有流量都代理了，可以绕过配置不足的问题。

环境变量设置: 某些情况下，脚本可能依赖特定的环境变量来配置网络连接。 如果这些变量没有被正确设置，也可能导致脚本执行失败。开启 TUN 模式后，系统会自动处理这些环境变量，问题可能就消失了。

3. 脚本的网络请求被其他应用或防火墙干扰:

防火墙规则: 你的系统或路由器的防火墙规则可能阻止了脚本的网络请求。 开启 TUN 模式后，所有的流量都会经过 Clash 的虚拟接口，可能绕过了某些防火墙规则，从而导致成功运行。

其他代理软件冲突: 如果你的系统中还运行着其他的代理软件，它们可能与 Clash 冲突，导致脚本的请求失败。开启 TUN 模式后，Clash 会接管所有的网络流量，其他软件的影响可能被排除。

具体原因分析步骤:

检查脚本内容: 查看 https://spotx-official.github.io/run.sh 的内容，看看其中是否涉及网络请求，是否使用了特定的域名或 IP 地址，是否对代理有特殊需求。

查看 Clash 日志: 在运行脚本前后，查看 Clash 的日志输出，看看是否有网络请求失败的提示，或者是否有与脚本相关的流量被拒绝。

尝试使用更精细的代理配置: 在不开启 TUN 模式的情况下，尝试根据脚本的网络请求目标，在 Clash 配置中添加更具体的代理规则，看看是否可以解决问题。

测试 DNS 解析: 尝试使用 nslookup 或 dig 等命令，在不开启 TUN 模式和开启 TUN 模式的情况下，分别测试脚本中使用的域名能否正确解析。

检查防火墙和网络设置: 检查你的系统防火墙和路由器设置，看看是否有阻止脚本网络请求的规则。

总结:

脚本必须在开启 Clash 增强模式 (TUN 模式) 下才能成功运行，很可能是因为它依赖于 TUN 模式下的代理能力，例如 DNS 解析、网络连接或透明代理。也可能是脚本自身配置不完善，或者网络环境的干扰造成的。你需要仔细分析脚本内容、Clash 日志，并逐步排查才能找到具体原因。

如果你能提供更多关于脚本内容或 Clash 日志的信息，我可以帮你更准确地分析问题。
...

### 🖥️ Terminal Input/Output

Last login: Sun Dec 29 14:21:41 on ttys000
@Mac ~ % bash <(curl -sSL https://spotx-official.github.io/run.sh)
curl: (35) Recv failure: Connection reset by peer

**Comment by jetfir3** [comment]
Hello.

The issue you have is caused by your network/computer settings conflicting with connections to *,github.io. 
It seems enabling "set as system proxy" resolved your issue based on your setup. So perhaps others in China with a similar setup will also resolve their issues with this as well. Thank you for sharing your experience.

Other alternatives can be found in the FAQ - https://github.com/SpotX-Official/SpotX-Bash/wiki/SpotX%E2%80%90Bash-FAQ#why-does-spotx-bash-say-failed-to-connect-could-not-be-resolved-or-other-curl-errors

There is another URL to try.. or users can simply download the spotx.sh file and run it locally. 

But all of these connection issues are unrelated to SpotX-Bash script directly and are an issue between the users network/computer settings and the Github URL(s), `*.github.io` or `raw.githubusercontent.com/*`
